[package]
name = "nas"
description = "Network-Attached Storage"
version = "0.1.0"
authors = ["Antonio Román <kyradiscord@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.2.1"
actix-web = "1.0.5"
actix-multipart = "0.1.2"
actix-files = "0.1.4"
futures = "0.1.28"
